import { MuseoModerno, Geist_Mono } from "next/font/google";
import "./globals.css";

const museomoderno = MuseoModerno({
  variable: "--font-museomoderno-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Billys Web Dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${museomoderno.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
